apiversion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
   matchLabels:
     app: postgre
  template:
   metadata:
      labels:
        app: postgre
  spec:
      containers:
      - name: postgre
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "kubedevnews"
        - name: POSTGRES_USER
          value: "kubedevnews"
        - name: POSTGRES_PASSWORD
          value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: yazzcastro/kube-news:v1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DB_DATABASE
          value: "kubedevnews"
        - name: DB_USERNAME
          value: "kubedevnews"
        - name: DB_PASSWORD
          value: "Pg#123"
        - name: DB_HOST
          value: "localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
      app: webapp
  type: NodePort  
  ports:
   - port: 80
     protocol: TCP
     targetPort: 8080
     nodePort: 30000
     name: http