name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker build kubenews
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            yazzcastro/kube-news:v1
            yazzcastro/kube-news:latest
    
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Autenticar o AWS CLI
        run: echo "Configurar o aws configure"
      - name: Configuração do Kubectl
        run: echo "Configurar o kubectl"
      - name: Deploy das aplicações
        run: echo "Executar o comando kubecetl apply"
